[package]
name = "calcit_paint"
version = "0.1.0"
authors = ["jiyinyiyong <jiyinyiyong@gmail.com>"]
edition = "2018"
exclude = ["resources", "!SourceCodePro-Medium.ttf"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calcit_runner = "0.3.19"
# calcit_runner = { path = "../calcit_runner.rs" }
# ggez = { path = "./ggez" }
ggez = { git = "https://github.com/ggez/ggez", branch = "devel" }
cirru_edn = "0.1.4"
cirru_parser = "0.1.1"
winit = "0.24"
notify = "4.0.16"
glam = { version = "0.12", features = ["mint"]}
im = "15.0.0"
lazy_static = "1.4.0"
lyon = "0.17.5"
