
[workspace]
resolver = "2"

[package]
name = "calcit_paint"
version = "0.0.1"
authors = ["jiyinyiyong <jiyinyiyong@gmail.com>"]
edition = "2018"
exclude = ["resources", "!SourceCodePro-Medium.ttf"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calcit_runner = "0.4.14"
# calcit_runner = { path = "../calcit_runner.rs" }
cirru_edn = "0.1.5"
cirru_parser = "0.1.1"
notify = "4.0.16"
im = "15.0.0"
lazy_static = "1.4.0"
env_logger = "0.9"
euclid = "0.22"
log = "0.4"
pixels = "0.6.0"
winit = "0.25"
raqote = "0.8.0"
glam = { version = "0.12", features = ["mint"]}
winit_input_helper = "0.10"


[[bin]]
name = "calcit_paint"
path = "src/main.rs"
