[package]
name = "calcit_paint"
version = "0.1.0"
authors = ["jiyinyiyong <jiyinyiyong@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calcit_runner = "0.3.13-a1"
ggez = "0.6.0-rc1"
cirru_edn = "0.1.4"
cirru_parser = "0.1.1"
winit = "0.24"
notify = "4.0.16"
glam = { version = "0.12", features = ["mint"]}
